[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/validation-key.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
