window.SaraViaConfig = {
  app: {
    name: 'Sara Via',
    version: '1.0.0',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'fr', 'tr'],
    rtlLanguages: ['ar'],
    currency: 'USD',
    storageKeys: {
      session: 'saravia.session',
      language: 'saravia.language',
      booking: 'saravia.booking',
      transactions: 'saravia.transactions',
      conversations: 'saravia.conversations'
    },
    heroRotateMs: 6500,
    typingMinMs: 900,
    typingMaxMs: 1800,
    paymentSuccessRate: 0.88,
    stripePublishableKey: 'pk_test_TYooMQauvdEDq54NiTphI7jx'
  },

  featuredDestinations: [
    { id: 'paris', city: 'Paris', country: 'France', query: 'Paris luxury travel', score: 96 },
    { id: 'dubai', city: 'Dubai', country: 'United Arab Emirates', query: 'Dubai luxury skyline hotel', score: 98 },
    { id: 'tokyo', city: 'Tokyo', country: 'Japan', query: 'Tokyo luxury city night', score: 95 },
    { id: 'istanbul', city: 'Istanbul', country: 'Türkiye', query: 'Istanbul Bosphorus luxury', score: 93 },
    { id: 'marrakech', city: 'Marrakech', country: 'Morocco', query: 'Marrakech luxury riad travel', score: 91 },
    { id: 'rome', city: 'Rome', country: 'Italy', query: 'Rome luxury travel', score: 94 }
  ],

  mock: {
    hotelPrefixes: ['Aurelia', 'Velora', 'Celestia', 'Opaline', 'Maison', 'Aster', 'Imperial'],
    hotelSuffixes: ['Grand Palace', 'Reserve', 'Collection', 'Residence', 'Signature Suites', 'Skyline Retreat', 'Private Estate'],
    perks: ['Private airport transfer', 'Michelin-curated dining', 'Ocean-view suite', 'Butler service', 'Spa ritual access', 'Flexible late checkout', 'Executive lounge access'],
    themes: ['romance', 'wellness', 'culture', 'shopping', 'culinary', 'coastal escape', 'city prestige'],
    quickQueries: {
      en: ['best places in Italy', 'luxury hotels in Dubai', 'romantic weekend in Paris', 'exclusive stay in Istanbul'],
      ar: ['أفضل الأماكن في إيطاليا', 'فنادق فاخرة في دبي', 'رحلة رومانسية في باريس', 'إقامة حصرية في إسطنبول'],
      fr: ['meilleurs endroits en Italie', 'hôtels de luxe à Dubaï', 'week-end romantique à Paris', 'séjour exclusif à Istanbul'],
      tr: ['İtalya\'da en iyi yerler', 'Dubai\'de lüks oteller', 'Paris\'te romantik hafta sonu', 'İstanbul\'da seçkin konaklama']
    }
  },

  i18n: {
    en: {
      languageName: 'English',
      common: {
        appName: 'Sara Via',
        login: 'Login',
        logout: 'Logout',
        search: 'Search',
        searching: 'Searching...',
        details: 'Details',
        confirm: 'Confirm',
        back: 'Back',
        close: 'Close',
        continue: 'Continue',
        secure: 'Secure',
        amount: 'Amount',
        status: 'Status',
        pending: 'Pending',
        success: 'Success',
        failed: 'Failed',
        language: 'Language',
        loading: 'Loading',
        yes: 'Yes',
        no: 'No',
        guest: 'Guest'
      },
      nav: {
        explore: 'Explore',
        concierge: 'Concierge',
        account: 'Account'
      },
      hero: {
        title: 'Luxury travel, intelligently orchestrated across the world.',
        subtitle: 'Sara Via blends destination discovery, premium stays, multilingual service, and secure payments into one global journey.',
        cta: 'Start your next journey',
        rotatingPrefix: 'Now spotlighting'
      },
      booking: {
        title: 'Premium booking engine',
        subtitle: 'Search cities or countries, review curated stays, and confirm a refined itinerary in minutes.',
        stepSearch: 'Search',
        stepResults: 'Results',
        stepDetails: 'Details',
        stepConfirm: 'Confirm',
        destinationLabel: 'City or country',
        destinationPlaceholder: 'Dubai, Italy, Paris, Tokyo...',
        checkInLabel: 'Check-in',
        checkOutLabel: 'Check-out',
        guestsLabel: 'Guests',
        guestsPlaceholder: '2',
        searchButton: 'Explore destinations',
        editSearch: 'Edit search',
        noResults: 'No matches were found. Refine your destination or dates and try again.',
        resultsTitle: 'Dynamic destination results',
        detailsTitle: 'Refined stay selection',
        confirmTitle: 'Guest details and payment',
        pickStay: 'Choose this stay',
        fromNight: 'from / night',
        itinerary: 'Suggested itinerary',
        amenities: 'Signature amenities',
        travelerName: 'Lead traveler name',
        travelerEmail: 'Lead traveler email',
        travelerNotes: 'Preferences',
        travelerNotesPlaceholder: 'Suite level, dining style, transfer preferences, celebration notes...',
        continueToPay: 'Continue to secure payment',
        signInRequired: 'Sign in to unlock checkout and saved journeys.',
        summary: 'Booking summary',
        total: 'Estimated total',
        paymentTitle: 'Stripe test checkout',
        paymentSubtitle: 'Use the card element below. Apple Pay or Google Pay appears when Stripe detects wallet availability.',
        protectedMessage: 'Checkout is protected. Sign in to continue.',
        confirmed: 'Your booking has been reserved in Sara Via.'
      },
      concierge: {
        title: 'AI travel concierge',
        subtitle: 'Ask for destinations, luxury hotels, or travel mood recommendations and get structured guidance instantly.',
        placeholder: 'Ask Sara Via about your next luxury trip...',
        send: 'Send',
        greeting: 'Welcome to Sara Via. I can curate destinations, stays, and premium travel ideas worldwide.',
        typing: 'Sara Via is preparing tailored recommendations...',
        sectionMatches: 'Best matches',
        sectionHotels: 'Luxury stays',
        sectionMoment: 'Travel moment',
        sectionAdvice: 'Concierge note'
      },
      auth: {
        title: 'Member access',
        subtitle: 'Sign in to protect bookings, payment flow, and concierge continuity.',
        email: 'Email address',
        password: 'Password',
        submit: 'Access Sara Via',
        helper: 'Use any valid email and a password with at least 6 characters.',
        signedIn: 'You are now signed in.',
        signedOut: 'You have been signed out.'
      },
      dashboard: {
        title: 'Protected account overview',
        subtitle: 'Track your secure session, recent transactions, and current itinerary state.',
        notSignedIn: 'Sign in to unlock your private travel dashboard.',
        signedInAs: 'Signed in as',
        token: 'Session token',
        transactions: 'Transactions',
        noTransactions: 'No payments yet. Once checkout succeeds, your transactions appear here.',
        liveBooking: 'Current booking state'
      },
      payment: {
        secureCheckout: 'Secure payment powered by Stripe test mode',
        walletReady: 'Wallet checkout is available on this device.',
        walletUnavailable: 'Apple Pay / Google Pay depends on browser and secure context availability.',
        cardLabel: 'Card details',
        payNow: 'Pay now',
        processing: 'Processing your payment securely...',
        success: 'Payment approved. Your booking is now confirmed.',
        failed: 'Payment was not completed. Review your card details and try again.',
        gatewayUnavailable: 'Stripe could not initialize. Card capture is unavailable in this environment.'
      },
      toast: {
        languageChanged: 'Language updated instantly.',
        loginRequired: 'Please sign in before payment.',
        searchInvalid: 'Please enter a valid destination and dates.',
        chooseStay: 'Select a luxury stay to continue.',
        travelerInvalid: 'Please enter a valid traveler name and email.'
      },
      validation: {
        destinationRequired: 'Destination is required.',
        datesRequired: 'Both travel dates are required.',
        datesOrder: 'Check-out must be after check-in.',
        guestsRequired: 'Guest count must be at least 1.',
        nameRequired: 'Traveler name is required.',
        emailRequired: 'A valid email is required.'
      },
      ai: {
        fallbackLocation: 'global luxury destinations',
        intro: 'Here is a curated luxury direction for your request.',
        note: 'I prioritized elegance, access, and premium service for this itinerary.'
      }
    },

    ar: {
      languageName: 'العربية',
      common: {
        appName: 'Sara Via',
        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        search: 'بحث',
        searching: 'جارٍ البحث...',
        details: 'التفاصيل',
        confirm: 'تأكيد',
        back: 'رجوع',
        close: 'إغلاق',
        continue: 'متابعة',
        secure: 'آمن',
        amount: 'المبلغ',
        status: 'الحالة',
        pending: 'قيد الانتظار',
        success: 'ناجح',
        failed: 'فشل',
        language: 'اللغة',
        loading: 'جارٍ التحميل',
        yes: 'نعم',
        no: 'لا',
        guest: 'زائر'
      },
      nav: {
        explore: 'استكشف',
        concierge: 'المساعد',
        account: 'الحساب'
      },
      hero: {
        title: 'سفر فاخر يُدار بذكاء على مستوى العالم.',
        subtitle: 'Sara Via تجمع اكتشاف الوجهات، والإقامات الراقية، والخدمة متعددة اللغات، والدفع الآمن في تجربة واحدة متكاملة.',
        cta: 'ابدأ رحلتك القادمة',
        rotatingPrefix: 'الوجهة المميزة الآن'
      },
      booking: {
        title: 'محرك حجز فاخر',
        subtitle: 'ابحث عن مدينة أو دولة، واستعرض إقامات مختارة، ثم أكمل رحلتك بخطوات سلسة.',
        stepSearch: 'بحث',
        stepResults: 'النتائج',
        stepDetails: 'التفاصيل',
        stepConfirm: 'التأكيد',
        destinationLabel: 'مدينة أو دولة',
        destinationPlaceholder: 'دبي، إيطاليا، باريس، طوكيو...',
        checkInLabel: 'تاريخ الوصول',
        checkOutLabel: 'تاريخ المغادرة',
        guestsLabel: 'عدد الضيوف',
        guestsPlaceholder: '2',
        searchButton: 'استكشاف الوجهات',
        editSearch: 'تعديل البحث',
        noResults: 'لم نجد نتائج مناسبة. عدّل الوجهة أو التواريخ ثم حاول مرة أخرى.',
        resultsTitle: 'نتائج وجهات ديناميكية',
        detailsTitle: 'اختيار إقامة راقية',
        confirmTitle: 'بيانات المسافر والدفع',
        pickStay: 'اختر هذه الإقامة',
        fromNight: 'ابتداءً من / ليلة',
        itinerary: 'برنامج مقترح',
        amenities: 'مزايا مميزة',
        travelerName: 'اسم المسافر الرئيسي',
        travelerEmail: 'بريد المسافر الرئيسي',
        travelerNotes: 'التفضيلات',
        travelerNotesPlaceholder: 'نوع الجناح، أسلوب الطعام، النقل، ملاحظات مناسبة خاصة...',
        continueToPay: 'المتابعة إلى الدفع الآمن',
        signInRequired: 'سجّل الدخول لفتح الدفع وحفظ الرحلات.',
        summary: 'ملخص الحجز',
        total: 'الإجمالي التقديري',
        paymentTitle: 'الدفع عبر Stripe بوضع الاختبار',
        paymentSubtitle: 'استخدم نموذج البطاقة أدناه. ستظهر Apple Pay أو Google Pay إذا كانت متاحة على جهازك.',
        protectedMessage: 'الدفع محمي. سجّل الدخول للمتابعة.',
        confirmed: 'تم حفظ حجزك داخل Sara Via.'
      },
      concierge: {
        title: 'المساعد الذكي للسفر',
        subtitle: 'اسأل عن وجهات أو فنادق فاخرة أو أساليب سفر، وستحصل على توصيات منظمة فورًا.',
        placeholder: 'اسأل Sara Via عن رحلتك الفاخرة القادمة...',
        send: 'إرسال',
        greeting: 'مرحبًا بك في Sara Via. أستطيع تنسيق وجهات وإقامات وأفكار سفر فاخرة حول العالم.',
        typing: 'Sara Via تُحضّر توصيات مصممة لك...',
        sectionMatches: 'أفضل الترشيحات',
        sectionHotels: 'إقامات فاخرة',
        sectionMoment: 'أجواء الرحلة',
        sectionAdvice: 'ملاحظة الكونسيرج'
      },
      auth: {
        title: 'دخول الأعضاء',
        subtitle: 'سجّل الدخول لحماية الحجز والدفع واستمرارية المساعد الذكي.',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        submit: 'الدخول إلى Sara Via',
        helper: 'استخدم بريدًا صحيحًا وكلمة مرور لا تقل عن 6 أحرف.',
        signedIn: 'تم تسجيل الدخول بنجاح.',
        signedOut: 'تم تسجيل الخروج.'
      },
      dashboard: {
        title: 'لوحة الحساب المحمية',
        subtitle: 'تابع الجلسة الآمنة، وآخر المعاملات، وحالة الرحلة الحالية.',
        notSignedIn: 'سجّل الدخول لفتح لوحة السفر الخاصة بك.',
        signedInAs: 'تم تسجيل الدخول باسم',
        token: 'رمز الجلسة',
        transactions: 'المعاملات',
        noTransactions: 'لا توجد مدفوعات بعد. عند نجاح الدفع ستظهر هنا.',
        liveBooking: 'حالة الحجز الحالية'
      },
      payment: {
        secureCheckout: 'دفع آمن عبر Stripe بوضع الاختبار',
        walletReady: 'الدفع بالمحفظة متاح على هذا الجهاز.',
        walletUnavailable: 'توفر Apple Pay أو Google Pay يعتمد على المتصفح والسياق الآمن.',
        cardLabel: 'بيانات البطاقة',
        payNow: 'ادفع الآن',
        processing: 'جارٍ معالجة الدفع بشكل آمن...',
        success: 'تمت الموافقة على الدفع، وأصبح الحجز مؤكدًا.',
        failed: 'لم يكتمل الدفع. راجع بيانات البطاقة ثم حاول مرة أخرى.',
        gatewayUnavailable: 'تعذر تهيئة Stripe في هذه البيئة.'
      },
      toast: {
        languageChanged: 'تم تغيير اللغة فورًا.',
        loginRequired: 'يجب تسجيل الدخول قبل الدفع.',
        searchInvalid: 'أدخل وجهة وتواريخ صحيحة.',
        chooseStay: 'اختر إقامة فاخرة للمتابعة.',
        travelerInvalid: 'أدخل اسم مسافر وبريدًا إلكترونيًا صحيحين.'
      },
      validation: {
        destinationRequired: 'الوجهة مطلوبة.',
        datesRequired: 'يجب إدخال تاريخي السفر.',
        datesOrder: 'يجب أن يكون تاريخ المغادرة بعد الوصول.',
        guestsRequired: 'يجب أن يكون عدد الضيوف 1 على الأقل.',
        nameRequired: 'اسم المسافر مطلوب.',
        emailRequired: 'البريد الإلكتروني الصحيح مطلوب.'
      },
      ai: {
        fallbackLocation: 'وجهات فاخرة حول العالم',
        intro: 'إليك توجيهًا فاخرًا مناسبًا لطلبك.',
        note: 'ركّزت على الأناقة وسهولة الوصول وجودة الخدمة في هذا الاقتراح.'
      }
    },

    fr: {
      languageName: 'Français',
      common: {
        appName: 'Sara Via',
        login: 'Connexion',
        logout: 'Déconnexion',
        search: 'Rechercher',
        searching: 'Recherche en cours...',
        details: 'Détails',
        confirm: 'Confirmer',
        back: 'Retour',
        close: 'Fermer',
        continue: 'Continuer',
        secure: 'Sécurisé',
        amount: 'Montant',
        status: 'Statut',
        pending: 'En attente',
        success: 'Succès',
        failed: 'Échec',
        language: 'Langue',
        loading: 'Chargement',
        yes: 'Oui',
        no: 'Non',
        guest: 'Invité'
      },
      nav: {
        explore: 'Explorer',
        concierge: 'Concierge',
        account: 'Compte'
      },
      hero: {
        title: 'Le voyage de luxe, intelligemment orchestré à l’échelle mondiale.',
        subtitle: 'Sara Via réunit découverte de destinations, séjours premium, service multilingue et paiement sécurisé dans une seule expérience.',
        cta: 'Commencer votre prochain voyage',
        rotatingPrefix: 'Destination mise en lumière'
      },
      booking: {
        title: 'Moteur de réservation premium',
        subtitle: 'Recherchez une ville ou un pays, comparez des séjours raffinés et confirmez un itinéraire élégant en quelques minutes.',
        stepSearch: 'Recherche',
        stepResults: 'Résultats',
        stepDetails: 'Détails',
        stepConfirm: 'Confirmation',
        destinationLabel: 'Ville ou pays',
        destinationPlaceholder: 'Dubaï, Italie, Paris, Tokyo...',
        checkInLabel: 'Arrivée',
        checkOutLabel: 'Départ',
        guestsLabel: 'Voyageurs',
        guestsPlaceholder: '2',
        searchButton: 'Explorer les destinations',
        editSearch: 'Modifier la recherche',
        noResults: 'Aucun résultat pertinent. Ajustez votre destination ou vos dates puis réessayez.',
        resultsTitle: 'Résultats dynamiques',
        detailsTitle: 'Sélection de séjour raffinée',
        confirmTitle: 'Coordonnées voyageur et paiement',
        pickStay: 'Choisir ce séjour',
        fromNight: 'à partir de / nuit',
        itinerary: 'Itinéraire suggéré',
        amenities: 'Prestations signature',
        travelerName: 'Nom du voyageur principal',
        travelerEmail: 'Email du voyageur principal',
        travelerNotes: 'Préférences',
        travelerNotesPlaceholder: 'Niveau de suite, style culinaire, transfert, notes de célébration...',
        continueToPay: 'Continuer vers le paiement sécurisé',
        signInRequired: 'Connectez-vous pour débloquer le paiement et vos voyages sauvegardés.',
        summary: 'Résumé de réservation',
        total: 'Total estimé',
        paymentTitle: 'Paiement Stripe en mode test',
        paymentSubtitle: 'Utilisez le formulaire carte ci-dessous. Apple Pay ou Google Pay s’affiche si disponible.',
        protectedMessage: 'Le paiement est protégé. Connectez-vous pour continuer.',
        confirmed: 'Votre réservation a été enregistrée dans Sara Via.'
      },
      concierge: {
        title: 'Concierge de voyage IA',
        subtitle: 'Demandez des destinations, hôtels de luxe ou inspirations et recevez une réponse structurée immédiatement.',
        placeholder: 'Demandez à Sara Via votre prochain voyage de luxe...',
        send: 'Envoyer',
        greeting: 'Bienvenue chez Sara Via. Je peux organiser destinations, séjours et inspirations premium dans le monde entier.',
        typing: 'Sara Via prépare des recommandations sur mesure...',
        sectionMatches: 'Meilleures options',
        sectionHotels: 'Séjours de luxe',
        sectionMoment: 'Moment de voyage',
        sectionAdvice: 'Note du concierge'
      },
      auth: {
        title: 'Accès membre',
        subtitle: 'Connectez-vous pour protéger réservations, paiement et continuité du concierge.',
        email: 'Adresse email',
        password: 'Mot de passe',
        submit: 'Accéder à Sara Via',
        helper: 'Utilisez un email valide et un mot de passe d’au moins 6 caractères.',
        signedIn: 'Connexion réussie.',
        signedOut: 'Vous avez été déconnecté.'
      },
      dashboard: {
        title: 'Espace compte protégé',
        subtitle: 'Suivez votre session sécurisée, vos transactions récentes et l’état actuel de votre réservation.',
        notSignedIn: 'Connectez-vous pour accéder à votre tableau de bord privé.',
        signedInAs: 'Connecté en tant que',
        token: 'Jeton de session',
        transactions: 'Transactions',
        noTransactions: 'Aucun paiement pour le moment. Après un paiement réussi, les transactions apparaîtront ici.',
        liveBooking: 'État actuel de la réservation'
      },
      payment: {
        secureCheckout: 'Paiement sécurisé via Stripe en mode test',
        walletReady: 'Le paiement par portefeuille est disponible sur cet appareil.',
        walletUnavailable: 'Apple Pay / Google Pay dépend du navigateur et du contexte sécurisé.',
        cardLabel: 'Informations carte',
        payNow: 'Payer maintenant',
        processing: 'Traitement sécurisé du paiement...',
        success: 'Paiement accepté. Votre réservation est confirmée.',
        failed: 'Le paiement n’a pas abouti. Vérifiez votre carte puis réessayez.',
        gatewayUnavailable: 'Stripe n’a pas pu être initialisé dans cet environnement.'
      },
      toast: {
        languageChanged: 'Langue mise à jour instantanément.',
        loginRequired: 'Veuillez vous connecter avant le paiement.',
        searchInvalid: 'Veuillez saisir une destination et des dates valides.',
        chooseStay: 'Choisissez un séjour de luxe pour continuer.',
        travelerInvalid: 'Veuillez saisir un nom et un email valides.'
      },
      validation: {
        destinationRequired: 'La destination est requise.',
        datesRequired: 'Les deux dates sont requises.',
        datesOrder: 'Le départ doit être après l’arrivée.',
        guestsRequired: 'Le nombre de voyageurs doit être au moins de 1.',
        nameRequired: 'Le nom du voyageur est requis.',
        emailRequired: 'Un email valide est requis.'
      },
      ai: {
        fallbackLocation: 'destinations de luxe mondiales',
        intro: 'Voici une orientation premium adaptée à votre demande.',
        note: 'J’ai priorisé élégance, accessibilité et qualité de service pour cet itinéraire.'
      }
    },

    tr: {
      languageName: 'Türkçe',
      common: {
        appName: 'Sara Via',
        login: 'Giriş yap',
        logout: 'Çıkış yap',
        search: 'Ara',
        searching: 'Aranıyor...',
        details: 'Detaylar',
        confirm: 'Onayla',
        back: 'Geri',
        close: 'Kapat',
        continue: 'Devam et',
        secure: 'Güvenli',
        amount: 'Tutar',
        status: 'Durum',
        pending: 'Beklemede',
        success: 'Başarılı',
        failed: 'Başarısız',
        language: 'Dil',
        loading: 'Yükleniyor',
        yes: 'Evet',
        no: 'Hayır',
        guest: 'Misafir'
      },
      nav: {
        explore: 'Keşfet',
        concierge: 'Concierge',
        account: 'Hesap'
      },
      hero: {
        title: 'Lüks seyahat, küresel ölçekte akıllıca yönetilir.',
        subtitle: 'Sara Via; destinasyon keşfi, premium konaklama, çok dilli hizmet ve güvenli ödemeyi tek bir yolculukta buluşturur.',
        cta: 'Bir sonraki yolculuğunu başlat',
        rotatingPrefix: 'Şu anda öne çıkan'
      },
      booking: {
        title: 'Premium rezervasyon motoru',
        subtitle: 'Şehir veya ülke arayın, seçkin konaklamaları inceleyin ve dakikalar içinde zarif bir seyahati onaylayın.',
        stepSearch: 'Arama',
        stepResults: 'Sonuçlar',
        stepDetails: 'Detaylar',
        stepConfirm: 'Onay',
        destinationLabel: 'Şehir veya ülke',
        destinationPlaceholder: 'Dubai, İtalya, Paris, Tokyo...',
        checkInLabel: 'Giriş',
        checkOutLabel: 'Çıkış',
        guestsLabel: 'Misafir',
        guestsPlaceholder: '2',
        searchButton: 'Destinasyonları keşfet',
        editSearch: 'Aramayı düzenle',
        noResults: 'Uygun eşleşme bulunamadı. Destinasyon veya tarihleri güncelleyip tekrar deneyin.',
        resultsTitle: 'Dinamik destinasyon sonuçları',
        detailsTitle: 'Seçkin konaklama seçimi',
        confirmTitle: 'Misafir bilgileri ve ödeme',
        pickStay: 'Bu konaklamayı seç',
        fromNight: 'başlangıç / gece',
        itinerary: 'Önerilen plan',
        amenities: 'Seçkin ayrıcalıklar',
        travelerName: 'Ana yolcu adı',
        travelerEmail: 'Ana yolcu e-postası',
        travelerNotes: 'Tercihler',
        travelerNotesPlaceholder: 'Süit seviyesi, yemek tarzı, transfer, kutlama notları...',
        continueToPay: 'Güvenli ödemeye devam et',
        signInRequired: 'Ödeme ve kayıtlı yolculuklar için giriş yapın.',
        summary: 'Rezervasyon özeti',
        total: 'Tahmini toplam',
        paymentTitle: 'Stripe test ödeme akışı',
        paymentSubtitle: 'Aşağıdaki kart alanını kullanın. Uygunsa Apple Pay veya Google Pay görünür.',
        protectedMessage: 'Ödeme korumalıdır. Devam etmek için giriş yapın.',
        confirmed: 'Rezervasyonunuz Sara Via içinde kaydedildi.'
      },
      concierge: {
        title: 'Yapay zekâ seyahat concierge',
        subtitle: 'Destinasyon, lüks otel veya seyahat ruhu sorun; anında yapılandırılmış öneri alın.',
        placeholder: 'Sara Via\'ya bir sonraki lüks seyahatinizi sorun...',
        send: 'Gönder',
        greeting: 'Sara Via\'ya hoş geldiniz. Dünya çapında destinasyon, konaklama ve premium seyahat fikirleri planlayabilirim.',
        typing: 'Sara Via size özel önerileri hazırlıyor...',
        sectionMatches: 'En iyi eşleşmeler',
        sectionHotels: 'Lüks konaklamalar',
        sectionMoment: 'Seyahat atmosferi',
        sectionAdvice: 'Concierge notu'
      },
      auth: {
        title: 'Üye erişimi',
        subtitle: 'Rezervasyon, ödeme akışı ve concierge sürekliliğini korumak için giriş yapın.',
        email: 'E-posta adresi',
        password: 'Şifre',
        submit: 'Sara Via\'ya eriş',
        helper: 'Geçerli bir e-posta ve en az 6 karakterli bir şifre kullanın.',
        signedIn: 'Giriş başarılı.',
        signedOut: 'Çıkış yapıldı.'
      },
      dashboard: {
        title: 'Korumalı hesap görünümü',
        subtitle: 'Güvenli oturumunuzu, son işlemleri ve mevcut rezervasyon durumunu izleyin.',
        notSignedIn: 'Özel seyahat panelinizi açmak için giriş yapın.',
        signedInAs: 'Giriş yapan kullanıcı',
        token: 'Oturum belirteci',
        transactions: 'İşlemler',
        noTransactions: 'Henüz ödeme yok. Başarılı ödeme sonrası işlemler burada görünür.',
        liveBooking: 'Mevcut rezervasyon durumu'
      },
      payment: {
        secureCheckout: 'Stripe test modu ile güvenli ödeme',
        walletReady: 'Cüzdan ile ödeme bu cihazda kullanılabilir.',
        walletUnavailable: 'Apple Pay / Google Pay tarayıcıya ve güvenli bağlama bağlıdır.',
        cardLabel: 'Kart bilgileri',
        payNow: 'Şimdi öde',
        processing: 'Ödemeniz güvenli biçimde işleniyor...',
        success: 'Ödeme onaylandı. Rezervasyonunuz artık kesinleşti.',
        failed: 'Ödeme tamamlanmadı. Kart bilgilerinizi kontrol edip tekrar deneyin.',
        gatewayUnavailable: 'Stripe bu ortamda başlatılamadı.'
      },
      toast: {
        languageChanged: 'Dil anında güncellendi.',
        loginRequired: 'Ödemeden önce giriş yapın.',
        searchInvalid: 'Lütfen geçerli bir destinasyon ve tarih girin.',
        chooseStay: 'Devam etmek için lüks bir konaklama seçin.',
        travelerInvalid: 'Lütfen geçerli bir yolcu adı ve e-postası girin.'
      },
      validation: {
        destinationRequired: 'Destinasyon gerekli.',
        datesRequired: 'Her iki seyahat tarihi de gerekli.',
        datesOrder: 'Çıkış tarihi girişten sonra olmalıdır.',
        guestsRequired: 'Misafir sayısı en az 1 olmalıdır.',
        nameRequired: 'Yolcu adı gerekli.',
        emailRequired: 'Geçerli bir e-posta gerekli.'
      },
      ai: {
        fallbackLocation: 'küresel lüks destinasyonlar',
        intro: 'İsteğinize uygun seçkin bir yönlendirme hazırladım.',
        note: 'Bu öneride zarafet, erişim ve yüksek hizmet kalitesine öncelik verdim.'
      }
    }
  }
};
